name: Download and Upload Funds Prices CSV

on:
  schedule:
    # cron 使用 UTC 时间，日本时间凌晨4点 = UTC 19:00 前一天
    - cron: '0 19 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync_funds:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas supabase tqdm openpyxl

      # 4️⃣ 设置环境变量（Supabase URL / Key）
      - name: Set environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> $GITHUB_ENV

      # 5️⃣ 运行 Python 脚本
      - name: Run fund CSV sync script
        run: |
          python scripts/download_and_upload_funds_prices_csv.py
