name: Stock Price Manual Test

on:
  workflow_dispatch:
    inputs:
      action:
        description: '选择执行操作'
        required: true
        default: fetch_us
        type: choice
        options:
          - fetch_us
          - fetch_jp
          - retry_us
          - retry_jp

jobs:
  stock-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade supabase
          pip install -r requirements.txt pandas_market_calendars yfinance

      - name: Set MARKET env
        run: |
          case "${{ github.event.inputs.action }}" in
            fetch_us)
                echo "MARKET=US" >> $GITHUB_ENV
                ;;
            fetch_jp)
                echo "MARKET=JP" >> $GITHUB_ENV
                ;;
            retry_us)
                echo "MARKET=US" >> $GITHUB_ENV
                echo "IS_RETRY=1" >> $GITHUB_ENV
                ;;
            retry_jp)
                echo "MARKET=JP" >> $GITHUB_ENV
                echo "IS_RETRY=1" >> $GITHUB_ENV
                ;;
          esac

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          MARKET: ${{ env.MARKET }}
          IS_RETRY: ${{ env.IS_RETRY }}
        run: |
          echo "[INFO] Running fetch_prices.py for $MARKET, RetryMode: $IS_RETRY"
          python scripts/fetch_prices.py
