name: Stock Price Automation

on:
  schedule:
    # 日股抓取：每天 16:00 JST → UTC 7:00
    - cron: "0 7 * * *"
    # 日股重试：每天 17:00 JST → UTC 8:00
    - cron: "0 8 * * *"
    # 美股抓取：每天 7:00 JST → UTC 22:00
    - cron: "0 22 * * *"
    # 美股重试：每天 8:00 JST → UTC 23:00
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  stock-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt pandas_market_calendars yfinance supabase
      - name: Determine Task
        id: set_task
        run: |
          UTC_HOUR=$(date -u +%H)

          if [ "$UTC_HOUR" -eq 7 ]; then
            echo "MARKET=JP" >> $GITHUB_ENV
          elif [ "$UTC_HOUR" -eq 8 ]; then
            echo "MARKET=JP" >> $GITHUB_ENV
            echo "IS_RETRY=1" >> $GITHUB_ENV
          elif [ "$UTC_HOUR" -eq 22 ]; then
            echo "MARKET=US" >> $GITHUB_ENV
          elif [ "$UTC_HOUR" -eq 23 ]; then
            echo "MARKET=US" >> $GITHUB_ENV
            echo "IS_RETRY=1" >> $GITHUB_ENV
          fi
      - name: Run Script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "MARKET=$MARKET"
          echo "IS_RETRY=$IS_RETRY"
          python scripts/fetch_prices.py
